version: '3.3'

services:
  db:
    build: db
    image: ludwigkolakowski/cloud-native-db:1.0.0

  words:
    build: words
    image: ludwigkolakowski/cloud-native-api:1.0.0
    deploy:
      replicas: 5

  web:
    build: web
    image: ludwigkolakowski/cloud-native-web:1.0.0
    ports:
      - '8080:80'
